### ISSUE TITLE
How to test the model

### ISSUE THREAD

**Issue by tangbinchn** [JasonBoy1/TextZoom#17]
After training according to your instructions, how to use the trained model to input a low-resolution picture and output a high-resolution picture.
Thanks for your work!

**Comment by tangbinchn** [comment]
> After training according to your instructions, how to use the trained model to input a low-resolution picture and output a high-resolution picture.
> Thanks for your work!

**Comment by YUAN-ANAN** [comment]
Hello，could you tell me how to test it?
