### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by xcc19970423** [JasonBoy1/TextZoom#18]
Hi,Jason Boy,When I run the main file, the following problem occurs:  '  lmdb.Error:  D:\TextSR\TextZoom\train1 : �ļ�����Ŀ¼��������﷨����ȷ�� '   can you tell me why?  thanks!

**Comment by JasonBoy1** [comment]
have you put the lmdb file in the right path?

**Comment by yjdqk** [comment]
you should put the train file in the right path
