### ISSUE TITLE
During training, loss_im is always 0

### ISSUE THREAD

**Issue by DongYongfei36** [JasonBoy1/TextZoom#21]
During training, loss_im is always 0
======================================================
evaling hard
[2020-11-07 19:22:42]   loss_rec 503.053| loss_im 0.000 PSNR 16.41 | SSIM 0.7024
save display images
aster_accuray: 34.92%
best_hard = 36.56%
evaling easy
[2020-11-07 19:24:23]   loss_rec 690.860| loss_im 0.000 PSNR 17.55 | SSIM 0.8102
save display images
aster_accuray: 68.50%
best_easy = 71.03%
evaling medium
[2020-11-07 19:25:58]   loss_rec 526.733| loss_im 0.000 PSNR 16.06 | SSIM 0.6451
save display images
aster_accuray: 50.82%
best_medium = 53.22%
[2020-11-07 19:26:15]   Epoch: [202][158/271]   vis_dir=vis     0.656
[2020-11-07 19:26:32]   Epoch: [202][258/271]   vis_dir=vis     0.426
======================================================
evaling hard
[2020-11-07 19:27:59]   loss_rec 439.905| loss_im 0.000 PSNR 16.15 | SSIM 0.6772
save display images
aster_accuray: 36.34%
best_hard = 36.56%
evaling easy
[2020-11-07 19:29:40]   loss_rec 500.382| loss_im 0.000 PSNR 17.28 | SSIM 0.7771
save display images
aster_accuray: 68.19%
best_easy = 71.03%
evaling medium
[2020-11-07 19:31:14]   loss_rec 485.999| loss_im 0.000 PSNR 15.99 | SSIM 0.6202
save display images
aster_accuray: 53.37%
best_medium = 53.37%*
[2020-11-07 19:31:30]   Epoch: [203][87/271]    vis_dir=vis     0.369
[2020-11-07 19:31:46]   Epoch: [203][187/271]   vis_dir=vis     0.429
======================================================

**Comment by DongYongfei36** [comment]
I solved this problem because base.py, loading model error，
if self.config.TRAIN.ngpu == 2

**Comment by DongYongfei36** [comment]
if self.args.arch != 'bicubic':
            model = model.to(self.device)
            image_crit.to(self.device)
            if cfg.ngpu >= 1:
                model = torch.nn.DataParallel(model, device_ids=range(cfg.ngpu))
                image_crit = torch.nn.DataParallel(image_crit, device_ids=range(cfg.ngpu))
            if self.resume is not '':
                print('loading pre-trained model from %s ' % self.resume)
                if self.config.TRAIN.ngpu == 2:     
                    model.load_state_dict(
                        torch.load(self.resume)['state_dict_G'], False)  # False 不报错，输出结果不对 
                        torch.load(self.resume)['state_dict_G'])         # 报错
                else:
                    model.load_state_dict({
                        'module.' + k: v
                        for k, v in torch.load(self.resume)
                        ['state_dict_G'].items()
                    })
        return {'model': model, 'crit': image_crit}

**Comment by YUAN-ANAN** [comment]
Hello, I also encountered the same problem, loss_im is still 0 after if self.config.TRAIN.ngpu == 2      Do you have any suggestions?

**Comment by YUAN-ANAN** [comment]
Hello, I also encountered the same problem, loss_im is still 0 . Do you have any suggestions?

**Comment by yjdqk** [comment]
does anybody have solve this question? during training,loss_im is still 0
