### ISSUE TITLE
read lmdb error

### ISSUE THREAD

**Issue by wyuzyf** [JasonBoy1/TextZoom#22]
buf.write(imgbuf)
TypeError: a bytes-like object is required, not 'NoneType'

**code:**

def buf2PIL(txn, key, type='RGB', degree=0):
    imgbuf = txn.get(key)
    buf = six.BytesIO()
    buf.write(imgbuf)
    buf.seek(0)
    im = Image.open(buf).convert(type)
    if degree is not 0:
        im = im.rotate(angle=degree, resample=Image.BICUBIC)
    return im

root = 'E:\\data\\TextZoom\\test\\easy'
env = lmdb.open(root)
txn = env.begin(write=False)

nSamples = int(txn.get(b'num-samples'))
print(nSamples)
# exit()
for index in range(nSamples):
    img_HR_key = b'image_hr-%09d' % index
    img_lr_key = b'image_lr-%09d' % index
    img_HR = buf2PIL(txn, img_HR_key, 'RGB')
    img_lr = buf2PIL(txn, img_lr_key, 'RGB')
    img_HR.show()

**Comment by JasonBoy1** [comment]
have you solved it?
