### ISSUE TITLE
Could you provide the images and labels? 

### ISSUE THREAD

**Issue by Peter2447** [JasonBoy1/TextZoom#23]
Hello, I'm very interested in your research. Could you please provide the SynLR picture in picture format and the label information in TXT format for the experiment in the paper? I want to make the LMDB dataset for the experiment by myself, thanks a lot.

**Comment by JasonBoy1** [comment]
You can easily generate the Synthetic LR by BICUBIC downsampling..

**Comment by Peter2447** [comment]
Thanks. And do you have the label information in TXT format? It Seens that I need that if I want to generate data in lmdb format.
