### ISSUE TITLE
Files missing?

### ISSUE THREAD

**Issue by pavlos13** [JasonBoy1/TextZoom#3]
Hello, I tried to run the code for training but I got this error. Maybe some files are missing from src?

I get it that we can download them from their original source, but it seems that you have edited the code and I cannot get it to run. So, if you could upload the aster and moran codes, we would be very grateful! 

https://github.com/JasonBoy1/TextZoom/blob/93330af08c125a1ed97e55a131e34bdb8e363ed2/src/model/tsrn.py#L13

> 
> > from .recognizer.tps_spatial_transformer import TPSSpatialTransformer
> > ModuleNotFoundError: No module named 'model.recognizer

**Comment by JasonBoy1** [comment]
Updated. sorry.
