### ISSUE TITLE
How to reproduce the published test accuracy

### ISSUE THREAD

**Issue by lmmx** [JasonBoy1/TextZoom#31]
Hey there, very happy to report I have managed to get your code up and running for both training and inference, and am now looking at how I can achieve the same impressive accuracy you wrote about in your paper.

- I added a note on the changes I made to get it to run in #30.

My train and infer code runs looked like:

```sh
conda activate textzoom

# Train
python main.py --batch_size=450 --STN --mask --gradient --vis_dir="vis" --resume="./ckpt/vis_11000/model_best.pth"

# Test
#python3 main.py --batch_size=300 --test --resume='./ckpt/vis_11000/model_best.pth' --STN --mask --gradient --vis_dir='vis'
# modify default `--test_data_dir` value in main.py rather than passing easy/medium/hard
for v in {01200,11000,40000}; do
  echo "vis_$v"
  python3 main.py --batch_size=300 --test --resume="./ckpt/vis_$v/model_best.pth" --STN --mask --gradient --vis_dir='vis'
done

# vis_11000 got best accuracy, though PSNR was smaller for 40000 (maybe overfit)

# Infer
python3 main.py --demo --demo_dir='../images/' --resume='./ckpt/vis_11000/model_best.pth' --STN --mask
```

Below are the `test` results I achieved up to 40,000 iterations, though it converged at 11,000:

> Easy:
> 
> - 1,200 iterations:  accuracy': 67.88%, avg PSNR: 22.296522, avg SSIM: 0.819532, FPS: 24.14789348904826
> - 11,000 iterations: accuracy': 70.97%, avg PSNR: 20.288235, avg SSIM: 0.833108, FPS: 25.541375967836526
> - 40,000 iterations: accuracy': 68.5%, avg PSNR: 17.607601, avg SSIM: 0.80518, FPS: 24.32865246802354
> 
> Medium:
> 
> - 1,200 iterations:  accuracy': 48.05%, avg PSNR: 18.763647, avg SSIM: 0.631675, FPS: 22.65210919969607
> - 11,000 iterations: accuracy': 54.08%, avg PSNR: 17.532022, avg SSIM: 0.647587, FPS: 23.9599626848633
> - 40,000 iterations: accuracy': 54.15%, avg PSNR: 15.900256, avg SSIM: 0.632104, FPS: 23.29499857043577
> 
> Hard:
> 
> - 1,200 iterations:  accuracy': 32.32%, avg PSNR: 19.515757, avg SSIM: 0.686933, FPS: 24.160339706382242
> - 11,000 iterations: accuracy': 36.93%, avg PSNR: 18.000088, avg SSIM: 0.71082, FPS: 23.196120059087583
> - 40,000 iterations: accuracy': 36.26%, avg PSNR: 16.265463, avg SSIM: 0.693389, FPS: 23.924821930943427

These are close enough to the train time accuracy (which were 38%, 55%, 71% for easy/medium/hard) though I think this is not as good as the (76%, 87%, 94%) reported in the paper.

The gap between the published accuracy and what I can reproduce is:

- 71% ⇢ 94% = +23%
- 54% ⇢ 87% = +33%
- 37% ⇢ 76% = +39%

Do you have any thoughts on this or suggestions on what might be causing the drop in performance?

**Comment by Imalne** [comment]
In my understanding, "94%", "87%" and "76%" is recognition accuracy of HR pictures.

**Comment by lmmx** [comment]
@Imalne Yes they are from the HR row of table 1 of the paper. That is what the test results should reproduce (the network converts images LR to HR and then runs text recognition, providing a measure of accuracy on the HR images). I did not see this. Interested to hear from others who did/didn’t get the same sort of recognition accuracy as me.

**Comment by Imalne** [comment]
In my understanding, HR Images means the groud truth images in the datasets. The results in table 4 represent the generated results from the network.

**Comment by Imalne** [comment]
In fact, the training results I got are similar to yours, a few percentage points less than the results in Table 4.

**Comment by lmmx** [comment]
Oh, can’t believe I missed that 🤦‍♂️ Then no issue after all, closing!

**Comment by hujikol** [comment]
hello @lmmx , is there any chance to share your converged model? 
I don't have the resource and time to do the entire training. 
Thank you for your kindness.
