### ISSUE TITLE
Error while training with lmdb dataset!

### ISSUE THREAD

**Issue by RamanHacks** [JasonBoy1/TextZoom#4]
There seems to be some problem with input dimension of image! 
Dimension mismatch occurs in the nn.Sequential block of STNHead:

`class STNHead(nn.Module):
  def __init__(self, in_planes, num_ctrlpoints, activation='none'):
    super(STNHead, self).__init__()

    self.in_planes = in_planes
    self.num_ctrlpoints = num_ctrlpoints
    self.activation = activation
    self.stn_convnet = nn.Sequential(
                          conv3x3_block(in_planes, 32), # 32*64
                          nn.MaxPool2d(kernel_size=2, stride=2),
                          conv3x3_block(32, 64), # 16*32
                          nn.MaxPool2d(kernel_size=2, stride=2),
                          conv3x3_block(64, 128), # 8*16
                          nn.MaxPool2d(kernel_size=2, stride=2),
                          conv3x3_block(128, 256), # 4*8
                          nn.MaxPool2d(kernel_size=2, stride=2),
                          conv3x3_block(256, 256), # 2*4,
                          nn.MaxPool2d(kernel_size=2, stride=2),
                          conv3x3_block(256, 256)) # 1*2`

![image](https://user-images.githubusercontent.com/17014540/93523990-7b07d700-f951-11ea-9d44-8b5229921600.png)

Please help!

**Comment by JasonBoy1** [comment]
What's your input image size?

**Comment by ZakiAIDev** [comment]
I used TextZomm dataset and i'm facing the same problem

**Comment by JasonBoy1** [comment]
The problem maybe the version of maxpooling in pytorch.
could you try this: change this around line 60 in model/tsrn.py:
```
def forward(self, x):
        if self.stn and self.training:
            **x = F.interpolate(x, (32, 64), mode='bilinear', align_corners=True)** 
            _, ctrl_points_x = self.stn_head(x)
            x, _ = self.tps(x, ctrl_points_x)
```

**Comment by RamanHacks** [comment]
I found the bug. The problem was with the forward pass of snt_convnet in stn_head.py file as it expects an input of 32*64 dimension. The input received after downscaling by a factor of 2 gets converted into 16*64 which is incompatible with the forward pass architecture. Resolved by changing the height in  config file from 32 to 64. I have raised a PR #5 corresponding to that and one more issue that occurs while training it on single gpu system! Please look into it and merge! Thanks!

**Comment by JasonBoy1** [comment]
> I found the bug. The problem was with the forward pass of snt_convnet in stn_head.py file as it expects an input of 32,64 dimension. The input received after downscaling by a factor of 2 gets converted into 16,64 which is incompatible with the forward pass architecture. Resolved by changing the height in config file from 32 to 64. I have raised a PR #5 corresponding to that and one more issue that occurs while training it on single gpu system! Please look into it and merge! Thanks!

Actually, I would not face this problem when I use input size as 128*32. I think this is because of the version of torch. The size of LR image is 64*16, while the 5 maxpooling would make 64/32=2, 16/32=0. While the maxpooling I used would make 16/32=1.
