### ISSUE TITLE
IndexError: index 3 is out of bounds for dimension 0 with size 3

### ISSUE THREAD

**Issue by zobeirraisi** [JasonBoy1/TextZoom#6]
I start the training the model but I got the following error:
`IndexError: index 3 is out of bounds for dimension 0 with size 3`
I think some labels or images in the `test/medium` are corrupted.

**Comment by JasonBoy1** [comment]
Sorry, could you paste more error info here? thanks

**Comment by ZakiAIDev** [comment]
Hello,

The same issue

`TextZoom/src/interfaces/base.py", line 173, in tripple_display
    tensor_in = image_in[i][:3,:,:]
IndexError: index 3 is out of bounds for dimension 0 with size 3`

**Comment by JasonBoy1** [comment]
image_in[i][:3,:,:], the slice operation will not exceed the index limitation, maybe the **i** is bigger than your batch_size ? The **i** is decided by your **n_vis** (number of visualization).

**Comment by ZakiAIDev** [comment]
the problem is just when we evaluate medium images. for easy and hard all is ok
I'm using 'batch_size = 128' and 'n_vis = 10' by default

**Comment by pavlos13** [comment]
A solution: 
On line 171 of base.py. change this:
'for i in (range(self.config.TRAIN.VAL.n_vis)):`

to this: 

`for i in (range(min(image_in.shape[0], self.config.TRAIN.VAL.n_vis) )):`

**Comment by JasonBoy1** [comment]
> A solution:
> On line 171 of base.py change this:
> `for i in (range(self.config.TRAIN.VAL.n_vis)):`
> to this:
> 
> `for i in (range(min(image_in.shape[0], self.config.TRAIN.VAL.n_vis) )):`

thanks
