### ISSUE TITLE
about create_lmdb.py

### ISSUE THREAD

**Issue by Uxasxie** [JasonBoy1/TextZoom#63]
你好，我使用create_lmdb.py之后生成的mdb文件放入测试路径却显示a bytes-like object is required, not 'NoneType'
![微信图片_20220801143702](https://user-images.githubusercontent.com/58348982/182087217-e729bfe4-1640-4e19-b5b9-89d6b1fd0237.png)
请问gt.txt文件里的格式是否如我写的这样呢？
![微信截图_20220801212458](https://user-images.githubusercontent.com/58348982/182158188-95973d36-f25d-4d23-bf29-5253ed1ba432.png)

**Comment by zmz1823** [comment]
Have you solved this problem yet? Can you tell me your solution?
