### ISSUE TITLE
Typo in super_resolution.py?

### ISSUE THREAD

**Issue by PAKALGUKSU** [JasonBoy1/TextZoom#7]
Think there's a typo in super_resolution.py, line 41.
Probably cfg.ckpr_dir should be changed to cfg.ckpt_dir.

`if not os.path.exists(cfg.ckpt_dir):
        os.makedirs(cfg.ckpr_dir)`

Thanks for sharing your work.

**Comment by JasonBoy1** [comment]
> Think there's a typo in super_resolution.py, line 41.
> Probably cfg.ckpr_dir should be changed to cfg.ckpt_dir.
> 
> `if not os.path.exists(cfg.ckpt_dir): os.makedirs(cfg.ckpr_dir)`
> 
> Thanks for sharing your work.

Thanks for your kindness. I will correct this typo.
