### ISSUE TITLE
Reading the images

### ISSUE THREAD

**Issue by Sagnik-C** [JasonBoy1/TextZoom#70]
Hey how do we read the images from the .mdb files? Kindly help me out with this as I need it for a project.

**Comment by WenjiaWang0312** [comment]
Sorry, it has been years since I quit OCR research and forgot about it. Could you check the code from [CRNN](https://github.com/meijieru/crnn.pytorch/blob/cdf07cc6d8dce0557e542e6cdc0558bd1ad66b53/dataset.py#L16)? I learned how to use lmdb from that.

**Comment by Sagnik-C** [comment]
Thanks a ton! I extracted the data.
