### ISSUE TITLE
Difference between TextSR and TextZoom

### ISSUE THREAD

**Issue by solitaire2015** [JasonBoy1/TextZoom#9]
As you say TextZoom is the upgrade version of TextSR, The methods are very different, TextSR uses GAN and Text Perceptual loss.  Do you have any experiment results between the old version GAN model and the new SR model?  Could you explain why you abandon Text Perceptual loss in the new version?

Best.

**Comment by JasonBoy1** [comment]
> As you say TextZoom is the upgrade version of TextSR, The methods are very different, TextSR uses GAN and Text Perceptual loss. Do you have any experiment results between the old version GAN model and the new SR model? Could you explain why you abandon Text Perceptual loss in the new version?
> 
> Best.

Actually, we redefined this problem and figure that we need a tiny and efficient  network. We also found that the so called "text perceptual loss" is not actually useful in our old version. The magical visualization results are mostly based on GAN.  By the way, that paper was strongly rejected. I am not saying that they are useless. I think the GAN and pre-trained recognition parameters could be combined in a more appropriate way in the following research.
